language: php
php:
    - 5.6
python:
    - 2.7
    - 3.4
matrix:
    allow_failures:
        -
            python: 3.4
sudo: false
before_install:
    - 'wget http://hiqdev.com/hidev/hidev.phar -O hidev.phar && chmod a+x hidev.phar'
    - './hidev.phar --version'
    - './hidev.phar travis/before_install'
install:
    - './hidev.phar travis/install'
script:
    - './hidev.phar travis/script'
